export class Product {
  constructor(
  public ProductId: number,
  public IsCombo: string,
  public CategoryId: number,
  public Name: string,
  public ShortDescription: string,
  public FullDescription: string,  
  public Pcs: number,
  public StandardPrice: number,
  public DiscountedPrice: number,
  public OldPrice: number,
  public Cost: number,
  public CoverImage: string,
  public CoverVideo: string,
  public IsFeatured: string,
  public IsShowOnHomePage: string,
  public DisplayOrder: number = 0,
  public MetaKeyWords: string,
  public MetaDescription: string,
  public MetaTitle: string,
  public Sku: string,
  public IsFreeShipping: string,
  public IsTaxExempt: string,
  public TaxCategoryId: number,
  public DisplayStockAvailability: string,
  public DisplayStockQuantity: string,
  public NotReturnable: string,
  public Weight: number,
  public Length: number,
  public Width: number,
  public Height: number,
  public ProductTags: string,
  public Manufacturer: string,
  public CreatedBy:number,
  public Brand: string,
  public FoodType: string,
  public HSNCode: string,
  public RetailerId: number,
  public ProductCode: string,
  public MinOrderQty: number,
  public ReturnPolicyDays :number,
  public Bulksection:any[]
  )
    {}
}

